# Generated by Django 4.0 on 2021-12-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NIK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Penduduk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik_pelapor', models.CharField(max_length=30)),
                ('nama_pelapor', models.CharField(max_length=50)),
                ('nama_terduga', models.CharField(max_length=50)),
                ('alamat_terduga', models.CharField(max_length=512)),
                ('gejala', models.CharField(max_length=512)),
                ('nama_petugas', models.CharField(max_length=50)),
                ('tgl_jemput', models.DateTimeField()),
                ('jumlah', models.IntegerField()),
            ],
        ),
    ]
