# Generated by Django 4.0 on 2021-12-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='jumlah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='nama_petugas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='tgl_jemput',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
