# Generated by Django 4.0 on 2021-12-28 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0002_alter_penduduk_jumlah_alter_penduduk_nama_petugas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penduduk',
            name='jumlah',
        ),
        migrations.RemoveField(
            model_name='penduduk',
            name='nama_petugas',
        ),
        migrations.RemoveField(
            model_name='penduduk',
            name='tgl_jemput',
        ),
    ]
