# Generated by Django 4.0 on 2021-12-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0003_remove_penduduk_jumlah_remove_penduduk_nama_petugas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_petugas', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_jemput', models.DateTimeField(blank=True, null=True)),
                ('jumlah', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
