# Generated by Django 4.0 on 2021-12-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverapp', '0004_petugas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Petugas',
        ),
        migrations.AddField(
            model_name='penduduk',
            name='jumlah',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='penduduk',
            name='nama_petugas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='penduduk',
            name='tgl_jemput',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
